/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        Verlag verlag = new Verlag();
        Kunde kunde = new Kunde(verlag);
        verlag.registerObserver(kunde);

        verlag.setZeitung("Zeitung","HEADLINE","DIESE GUTE");
        verlag.removeObserver(kunde);

        verlag.setZeitung("NIX","PRINT","DIESE GUTE");
    }
}
