import Person.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Person fabian = new Fabian();
        fabian.display();
        fabian.showOutfit();

        System.out.println();

        Person karim = new Karim();
        karim.display();
        karim.showOutfit();

        System.out.println();

        Person jeff = new Jeff();
        jeff.display();
        jeff.showOutfit();

        System.out.println();

        Person baer = new FettesBaer();
        baer.display();
        baer.showOutfit();
    }
}
